/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OsSelectRouteImport } from './routes/os-select'
import { Route as ModeSelectRouteImport } from './routes/mode-select'
import { Route as LoadingRedRouteImport } from './routes/loading-red'
import { Route as LoadingBlueRouteImport } from './routes/loading-blue'
import { Route as IndexRouteImport } from './routes/index'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OsSelectRoute = OsSelectRouteImport.update({
  id: '/os-select',
  path: '/os-select',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeSelectRoute = ModeSelectRouteImport.update({
  id: '/mode-select',
  path: '/mode-select',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRedRoute = LoadingRedRouteImport.update({
  id: '/loading-red',
  path: '/loading-red',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingBlueRoute = LoadingBlueRouteImport.update({
  id: '/loading-blue',
  path: '/loading-blue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loading-blue': typeof LoadingBlueRoute
  '/loading-red': typeof LoadingRedRoute
  '/mode-select': typeof ModeSelectRoute
  '/os-select': typeof OsSelectRoute
  '/portfolio': typeof PortfolioRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loading-blue': typeof LoadingBlueRoute
  '/loading-red': typeof LoadingRedRoute
  '/mode-select': typeof ModeSelectRoute
  '/os-select': typeof OsSelectRoute
  '/portfolio': typeof PortfolioRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loading-blue': typeof LoadingBlueRoute
  '/loading-red': typeof LoadingRedRoute
  '/mode-select': typeof ModeSelectRoute
  '/os-select': typeof OsSelectRoute
  '/portfolio': typeof PortfolioRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loading-blue'
    | '/loading-red'
    | '/mode-select'
    | '/os-select'
    | '/portfolio'
    | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loading-blue'
    | '/loading-red'
    | '/mode-select'
    | '/os-select'
    | '/portfolio'
    | '/terminal'
  id:
    | '__root__'
    | '/'
    | '/loading-blue'
    | '/loading-red'
    | '/mode-select'
    | '/os-select'
    | '/portfolio'
    | '/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadingBlueRoute: typeof LoadingBlueRoute
  LoadingRedRoute: typeof LoadingRedRoute
  ModeSelectRoute: typeof ModeSelectRoute
  OsSelectRoute: typeof OsSelectRoute
  PortfolioRoute: typeof PortfolioRoute
  TerminalRoute: typeof TerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os-select': {
      id: '/os-select'
      path: '/os-select'
      fullPath: '/os-select'
      preLoaderRoute: typeof OsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode-select': {
      id: '/mode-select'
      path: '/mode-select'
      fullPath: '/mode-select'
      preLoaderRoute: typeof ModeSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading-red': {
      id: '/loading-red'
      path: '/loading-red'
      fullPath: '/loading-red'
      preLoaderRoute: typeof LoadingRedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading-blue': {
      id: '/loading-blue'
      path: '/loading-blue'
      fullPath: '/loading-blue'
      preLoaderRoute: typeof LoadingBlueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadingBlueRoute: LoadingBlueRoute,
  LoadingRedRoute: LoadingRedRoute,
  ModeSelectRoute: ModeSelectRoute,
  OsSelectRoute: OsSelectRoute,
  PortfolioRoute: PortfolioRoute,
  TerminalRoute: TerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
